### ISSUE TITLE
Consider interaction with Storage partitioning

### ISSUE THREAD

**Issue by bvandersloot-mozilla** [privacycg/storage-access-headers#1]
How does this interact with storage departitioning that Ari has proposed as well?

I'm optimistic that if this conveys those semantics as well, we can resolve all of the outstanding issues tied to [storage-partitioning/issues/32](https://github.com/privacycg/storage-partitioning/issues/32)

**Comment by cfredric** [comment]
I think the right answer might be "it doesn't".

The request header in this proposal only addresses the "are unpartitioned cookies accessible" or "could unpartitioned cookies trivially become accessible" use case, for cross-site requests. That use case boils down to asking whether the context has the `storage-access` permission already, and if so, has it been "activated" yet.

Whether or not an iframe has gotten a `handle` (and if so, which storage backends did it request access to?) via the proposal in https://github.com/arichiv/saa-non-cookie-storage is a different question from whether the iframe has the `storage-access` permission in the first place.

I'd rather not make the `Sec-Fetch-Storage-Access` header responsible for conveying info about the context's partitioning in general, since that's a much larger question with less clear requirements.

**Comment by johannhof** [comment]
Yeah, there are two parts to this, I think

1) I agree this can't interact with non-cookie storage in any significant way, at least I don't see how :)
2) We should probably clarify the relationship of this proposal to https://github.com/privacycg/storage-partitioning/issues/32 in the README.
