### ISSUE TITLE
Document security caveats of setting the `Activate-Storage-Access: retry` header

### ISSUE THREAD

**Issue by arturjanc** [privacycg/storage-access-headers#7]
#### Overview

I've been mulling over the relationship between an iframe calling `document.requestStorageAccess()` and a (non-iframe) subresource setting `Activate-Storage-Access: retry` and figured there's enough of a semantic difference that we might want to give slightly more specific guidance about the use of the header.

In short, setting `Activate-Storage-Access: retry` on any resource by design exposes that resource to cross-site leaks because it allows any top-level context with storage access to the site hosting the resource to load the resource with credentials. Any resource loaded in `no-cors` mode that could contain interesting data (e.g. an image of a script) which sets the header will be directly loadable with 1P cookies by an attacking site. The only condition is that the attacking site has obtained storage access permission for the site of the embedded resource (e.g. loaded an unrelated widget from that site which legitimately requested storage access).

Note that this risk is different in kind than an iframe calling `document.requestStorageAccess()` and then being vulnerable from attacks by its cross-site embedder. This is because receiving storage access doesn't, by default, expose the contents of a cross-site iframe to the embedder (because of SOP protections, iframes usually being out-of-process, etc). Also, currently, an iframe that asks for storage access doesn't introduce risks for other content on its hosting site because the permission is only scoped to the current iframe load, and possibly any endpoints that the iframe navigates itself to. Finally, iframes have fine-grained controls over embedding (e.g. using CSP's `frame-ancestors`) so you can allowlist specific origins that are allowed to embed an iframe that requests storage access.

#### Example
Imagine the following scenario:
1. calendar.com/special has an iframe-based widget embeddable only by special-calendar.com, which calls rSA to load the user's calendar in the iframe.
    * calendar.com/special/profile.png returns the current user's profile picture to be directly embeddable (outside of an iframe) by special-calendar.com. The image sets `Activate-Storage-Access: retry` to allow this.
2. calendar.com also has a general-purpose calendar widget embeddable by any site which calls rSA.

In this case, if example.com embeds the general-purpose calendar widget and obtains storage access, it will also be able to load the user's authenticated profile picture even if that resource is only meant to be directly loaded by special-calendar.com.

Essentially, the problem here is caused by the coarse-grained nature of the `Activate-Storage-Access` header which ties the load of the authenticated resource to a storage access permission, and not to an origin that is privileged to make the credentialed requests to a given resource.

Also note that `no-cors` resources such as images, etc. don't have fine-grained embedding controls so there's no way to allow the image to be embedded only by special-calendar.com and not other sites (except for using brittle approaches such as checking the `Referer` header).

#### Fixes
This is somewhat tricky, but there's a spectrum of things we could do:
1. Require `Activate-Storage-Access` to specify not only permission, but also the origin that is meant to receive the ability to load the resource with credentials.
    * For example, CORS requires specifying the requesting origin in the `Access-Control-Allow-Origin` response header, which can be the `*` wildcard for unauthenticated requests, but needs to be the specific origin for credentialed requests.
    * We could follow a similar model, or be more permissive and _always_ allow setting a wildcard (e.g. `Activate-Storage-Access: retry; allowed-origin=*`)
2. Add the `Origin` request header when we're retrying to send request with credentials. This is still unsafe by default, but at least attaches trustworthy information that lets the server control which origins can make credentialed requests (so that servers could implement server-side logic to only respond to requests from allowlisted origins).
3. Document that using the `Activate-Storage-Access`  header may be dangerous. YOLO.

**Comment by cfredric** [comment]
Thanks Artur, I appreciate you thinking about these risks and outlining them explicitly.

My goal had been to delegate all of the security decisions to the server (after having provided trustworthy information from the UA, in the form of the `Origin` header).

But I like the idea of adding an origin allowlist to the `Activate-Storage-Access: retry` value. That still gives the server full control over security, and makes behavior safe by default. It also avoids requiring the UA to send any more info than it does now (e.g. doesn't require the `Origin` header), which is better from a privacy PoV. In particular, I hadn't realized that the `Origin` header is omitted for x-origin media element requests, which is one of the motivating use cases for this proposal.

I think it's ok (and maybe necessary?) to be a little more lax, and always allow a wildcard allowlist (`allowed-origin=*`), as long as the allowlist's default value is empty. WDYT?

**Comment by johannhof** [comment]
As it happens I was chatting about SAA headers with @annevk yesterday and he raised a very similar concern. I think requiring the origin to be specified as part of the headers is reasonable. I don't have a strong opinion on the wildcard, maybe we could leave it out pending strong developer feedback that it's needed?

**Comment by cfredric** [comment]
> I unfortunately don't think this would work - we generally need to give the server a trustworthy signal about the origin from which the request is made

I see. So IIUC, we'd have to require that the server specify the origin in the `Activate-Storage-Access` header, *and also* modify the browser's handling of the `Origin` header such that it is sent on all* cross-origin requests (including images, videos, etc). Otherwise, the server would not always receive that trustworthy signal, IIUC.

*Perhaps we can avoid attaching the `Origin` header in new cases *except* when the `storage-access` permission has already been granted between those two sites (and the request would otherwise be uncredentialed), since in those cases, there isn't a meaningful privacy boundary to enforce. (I'm assuming that privacy is the reason why the `Origin` header is omitted in some cases; but I haven't found the relevant section in the Fetch spec yet, and don't have historical context.)

**Comment by annevk** [comment]
It's omitted because including it in every request confuses servers unfortunately. Perhaps the servers having knowledge of `storage-access` is a sufficient opt-in however.

**Comment by johannhof** [comment]
Yeah I agree that's probably the way we'd have to handle it. If storage access is "granted" then the `Origin` header needs to be sent in order to "activate" it. In other cases it's not necessary, AFAIU.

The one thorny edge case here is ABA, as always. ABA embeds should be able to use SAA headers to get storage access without an actual storage access permission being present, so what do we send?

**Comment by johannhof** [comment]
> > The one thorny edge case here is ABA, as always. ABA embeds should be able to use SAA headers to get storage access without an actual storage access permission being present, so what do we send?
> 
> Good call-out. IMO the most natural option would be to send `Sec-Fetch-Storage-Access: inactive` for ABA requests, since those contexts behave as if they have permission anyway (via the "same authority" auto-resolve in `hasStorageAccess()` and `requestStorageAccess()`).

We should try that, it seems most consistent to me, I hope we're not hitting any of these servers that get confused by Origin headers in ABA settings :)

**Comment by cfredric** [comment]
I'm going to adopt this into the explainer and amend the "retry" header to be a [sf-dictionary](https://datatracker.ietf.org/doc/html/rfc8941#dictionary), so in practice this would look something like `Activate-Storage-Access: retry="https://foo.bar.com"`. I.e., the server would need to echo the request initiator origin in its opt-in. Wildcards will be supported.

Additionally, I'll add the requirement that the UA include the `Origin` header on requests that send `Sec-Fetch-Storage-Access: inactive`, so that the server can make an informed choice. (The behavior for requests that send `Sec-Fetch-Storage-Access: none` or `Sec-Fetch-Storage-Access: active`, or omit the header entirely, doesn't need to change.)

(Posting this here now, so people can chime in with concerns before I spend too much time drafting a PR.)

**Comment by cfredric** [comment]
Closing this now, per #14. Feel free to reopen if anyone feels this isn't addressed properly yet!
